pull_request_rules:
  - name: automatic merge for main when the title does not contain “WIP” (ignoring case)
    conditions:
      - base=main
      - -title~=(?i)wip
    actions:
      merge:
        method: merge

